{
    "milestones": [
        {
            "milestone": "test_add_option",
            "triggers": [ { "type": "game_start" } ],
            "visible": false,
            "drop": "true",
            "description": "",
            "goal": "",
            "changes": [ { "type": "add_option", "name": "$$self.name", "option": "测试" } ],
            "dialogs": [],
            "subsequences": []
        },
        {
            "milestone": "test_option_clicked",
            "triggers": [ { "type": "option_dialog", "name": "$$self.name", "option": "测试" } ],
            "visible": false,
            "drop": "false",
            "description": "",
            "goal": "",
            "changes": [],
            "dialogs": [
                {
                    "list": [
                        { "speaker": "$$self.name", "content": "你确定要测试吗？", "label": "", "voice": "" },
                        [
                            {
                                "condition": "",
                                "option": "确定",
                                "dialogs": [ { "list": [ { "speaker": "$$self.name", "content": "成功", "label": "", "voice": "" } ] } ],
                                "changes": []
                            },
                            {
                                "condition": "",
                                "option": "取消",
                                "dialogs": [ { "list": [ { "speaker": "$$self.name", "content": "已取消", "label": "", "voice": "" } ] } ],
                                "changes": []
                            }
                        ]
                    ]
                }
            ],
            "subsequences": []
        }
    ]
}
